// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ems/handler"
	"ems/repository"
	"ems/services"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitializeEmployeeHandler(pool *pgxpool.Pool) *handler.EmployeeHandler {
	employeeRepository := repository.NewEmployeeRepository(pool)
	employeeService := services.NewEmployeeService(employeeRepository)
	employeeHandler := handler.NewEmployeeHandler(employeeService)
	return employeeHandler
}

func InitializeDepartmentHandler(pool *pgxpool.Pool) *handler.DepartmentHandler {
	departmentRepository := repository.NewDepartment(pool)
	departmentService := services.NewDepartmentService(departmentRepository)
	departmentHandler := handler.NewDepartmentHandler(departmentService)
	return departmentHandler
}

func InitializeAssetHandler(pool *pgxpool.Pool) *handler.AssetHandler {
	assetsRepository := repository.NewAssetRepository(pool)
	assetService := services.NewAssetService(assetsRepository)
	assetHandler := handler.NewAssetHandler(assetService)
	return assetHandler
}

func InitializeSalaryHandler(pool *pgxpool.Pool) *handler.SalaryCategoryHandler {
	salaryCategoryRepository := repository.NewSalaryCategoryRepository(pool)
	salaryCategoryService := services.NewSalaryCategoryService(salaryCategoryRepository)
	salaryCategoryHandler := handler.NewSalaryCategoryHandler(salaryCategoryService)
	return salaryCategoryHandler
}
